language: python
python:
  - "3.3"
  - "2.7"
  - "2.6"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -r requirements-dev.txt
# command to run tests, e.g. python setup.py test
script:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then coverage run -m unittest2.__main__ discover; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then coverage run -m unittest discover; fi
after_success: coveralls
